name: CI Class

on:
   push:
     branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependências
      working-directory: CinemaList
      run: npm install
    
    - name: Install Angular CLI
      working-directory: CinemaList
      run: npm install -g @angular/cli

    - name: Executar testes
      working-directory: CinemaList
      run: npm run test